version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=finp2p
      - POSTGRES_PASSWORD=finp2p
      - POSTGRES_DB=finp2p
    volumes:
      - finp2p_pg_data:/bitnami/postgresql
volumes:
  finp2p_pg_data: